title: Peter A Tkatchenko
logo: /assets/img/me_40percentsmaller.jpg
description: Aspiring economist, socially-conscious philosophical thought appreciator
show_downloads: true
theme: jekyll-theme-minimal
